export { DateTime } from "./DateTime";
export { getDDG } from "../api/getDDG";
export { flipCoin } from "./flipCoin";
export { getJokes } from "../api/getJokes";
export { getWeather } from "../api/getWeather";
export { greet } from "./greet";
export { speechToText } from "./speechToText";
export { textToSpeech } from "./textToSpeech";
export { bot } from "./bot";
